name: build and release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and release binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: Install musl and musl-gcc
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      - name: Get templ version
        run: echo "TEMPL_VERSION=$(grep 'github.com/a-h/templ' go.mod | awk '{print $2}')" >> $GITHUB_ENV
      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@${{ env.TEMPL_VERSION }}
      - uses: extractions/setup-just@v2
      - name: Build binary
        run: just build
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: pyramid-exe
